name: Docker Build

on:
  push:
    branches:
      - disabled

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Images
      run: |
        IMAGE_NAME="opencopilot/${{ matrix.os }}-backend"
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME backend/
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push $IMAGE_NAME

        IMAGE_NAME="opencopilot/${{ matrix.os }}-llm-server"
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME llm-server/
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push $IMAGE_NAME

      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
